export { default as Navbar } from "./navbar";
export { default as Profile } from "./profile";
export { default as Login } from "./login";
export { default as Register } from "./register";
export { default as Routines } from "./routines";
export { default as AddRoutine } from "./addroutine";
export { default as Activities } from "./activities";
export { default as Home } from "./home";
export { default as AddActivity } from "./addactivity";
